apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po
spec:
  containers:
    -
      args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
      command:
        - php
      image: omaeec/redhat-php:latest@sha256:9062867573cec1b9beac84c2f36de36cc2eff07a06f9dfbe7c64bfb8291046e0
      name: phpinfo-contaniner
      ports:
        - 
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
      workingDir: /src/
  volumes:
    -
      configMap:
        defaultMode: 0400
        items: 
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
