apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po
spec:
  containers:
    -
      args:
        - -f src/index.php -S 0.0.0.0:8080
      command:
        - php
      image: eleigle/redhat-php:latest
      name: phpinfo-container
      ports:
        -
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
      workingDir: /src/
  volumes:
    -
      configMap:
        defaultMode: 0400
        items:
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
