apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po
  labels: 
    app: phpinfo
    env: production
    tier: frontend
spec:
  containers:
    -
      args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
      command:
        - php
      image: omaeec/redhat-php:latest@sha256:985fb1b8ce438cb03554d00ec9002e382f1154f42b8808c1d203e9e834e4213c
      name: phpinfo-contaniner
      ports:
        - 
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
      workingDir: /src/
  volumes:
    -
      configMap:
        defaultMode: 0400
        items: 
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: phpinfo-svc
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: phpinfo
    env: production
    tier: frontend
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: phpinfo-route
spec:
  to: 
    kind: Service
    name: phpinfo-svc
